### ISSUE TITLE
Create Sign-up Event pages

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#22] opened 2015-04-17 02:46 UTC
@nodeschool/international-day  Usually at events we many people use signup pages. It would be good to have meetup/ti.to/doorkeeper/etc. pages for the international-day of each chapter. If done could you post them here or add them to the csv that is part of #19  ?

**Comment by jeduan** [comment] 2015-04-17 02:51
Only have used eventbrite and meetup, but seen ti.to in many places. Any advantage of using it or doorkeeper?

**Comment by martinheidegger** [comment] 2015-04-17 03:32
Doorkeeper is for free (unlimited size)

**Comment by finnp** [comment] 2015-04-17 06:37
Ti.to is free as well and easier to use than meetup.

**Comment by bajtos** [comment] 2015-04-17 06:37
Hradec Králové: http://srazy.info/nodeschool/5323

**Comment by iancrowther** [comment] 2015-04-17 10:40
London: https://ti.to/nodeschool/international-nodeschool-day-london

**Comment by iancrowther** [comment] 2015-04-17 10:49
@martinheidegger am wondering what the need for this is?

@all I was planning to ask each chapter to add its attendees to the [international-day team](https://github.com/orgs/nodeschool/teams/international-day) and then use the api to render an attendee rollcall on the website.  I figure this is a much easier approach. 

As were getting closer to the day, I think we should focus on adding structure to the day.  We need to flesh out the [participating](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md) guide and distribute it to each chapter who has listed in.

**Comment by iancrowther** [comment] 2015-04-17 10:53
we could/should setup an international-day-2015 team to keep the rollcall clean

**Comment by tdd** [comment] 2015-04-17 10:54
Hey guys,

FWIW, regarding the Paris chapter:

• We use Meetup (I'll open the sign-up this weekend, we've got a loooong 
waiting list already)

• We plan on a "normal" NodeSchool day, as per the 2 previous ones (Feb 
21, Apr 11), in the spirit of the original NS: free day where attendees 
come with laptops (or pair up) and get to discover Node/JS through 
tackling NodeSchool-listed workshops with the help of ~6 mentors and 
other attendees.

We provide free top-notch catering, too, and some structure to it all 
(detailed intro, get-started demo, list of intros to all existing 
workshops, etc.).

We try to make this happen every 6 weeks or so, always on a Saturday, 
always at Mozilla Paris.

Best,

## 

Christophe Porteneuve
tdd@tddsworld.com

**Comment by martinheidegger** [comment] 2015-04-17 11:23
@iancrowther Well, the meeting places we have are usually at an address. Occasionally they might to be hard to find but always its good to know them :) Usually those sites have a section regarding access that makes the place easier to find. The spaces usually have a limited amount of space. Knowing how many people can attend makes thing easier for the attendees. The organisers have to be at that place from a certain time until a certain time in my understanding: The event pages usually also have a sort of agenda that allows attendees to know when a person will be at the place (and when they plan to be out for lunch)

**Comment by iancrowther** [comment] 2015-04-17 11:30
@martinheidegger - I know its a pain, but can you feed this into https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md

**Comment by tdd** [comment] 2015-04-21 13:41
Paris: http://www.meetup.com/NodeSchool-Paris/events/221935923/

**Comment by martinheidegger** [comment] 2015-04-22 04:16
Osaka: https://nodeschool.doorkeeper.jp/events/23614

**Comment by gangstead** [comment] 2015-04-22 17:26
Dallas (Texas): http://www.meetup.com/Nodeschool-Dallas/events/219510533/

**Comment by blakmatrix** [comment] 2015-04-22 17:28
Seattle: http://www.meetup.com/Seattle-NodeSchool/events/221984469/

**Comment by alexfernandez** [comment] 2015-04-22 21:11
Madrid: http://www.meetup.com/Node-js-Madrid/events/222023643/

**Comment by foliveira** [comment] 2015-04-24 15:17
Lisbon: http://www.meetup.com/require-lx/events/221544407/

**Comment by jeduan** [comment] 2015-04-24 19:03
Mexico City: http://www.meetup.com/ChelaJS/events/222073841/

**Comment by lvivier** [comment] 2015-04-27 17:03
Vancouver: https://ti.to/nodeschool-vancouver/2015-05-23

**Comment by yosuke-furukawa** [comment] 2015-04-30 01:12
Tokyo: http://nodejs.connpass.com/event/14741/

**Comment by martinheidegger** [comment] 2015-05-01 11:44
Hey, 
- [x] @yoshuawuyts
- [x] @awaterma 
- [x] @paulohp 
- [x] @finnp 
- [ ] @ralucas 
- [ ] @davyengone 
- [x] @a0viedo 
- [x] @no9 
- [x] @keokilee 
- [x] @bajtos 
- [ ] @hrayatnia 
- [x] @mcollina 
- [x] @jonotron 
- [ ] @usmantahirr  
- [x] @makenai 
- [x] @julianduque 
- [x] @timoxley 
- [x] @pricco 
- [x] @spikeheap
- [ ] @carlodicelico 
- [x] @majgis 
- [ ] @colinloretz 
- [ ] @marinintim 
- [x] @llkats 
- [x] @gaboesquivel 
- [ ] @forres 
- [x] @blakmatrix
- [x] @beltran-rubo
- [x] @afronski
- [x] @jeffjewiss
- [x] @sequoia 
- [x] @grabbou
- [x] @cronopio
- [x] @diegowifi
- [ ] @chitopolo
- [x] @kwakayama
- [x] @ryanramage
- [x] @gmauricio 
- [x] @az7arul
- [ ] @iamchathu

23days until international day! It would be good to have your event sites!

**Comment by spikeheap** [comment] 2015-05-01 12:11
Oxford: http://www.meetup.com/JSOxford/events/222015476/

**Comment by spikeheap** [comment] 2015-05-01 12:16
For future events it might be worth trying yaml (or whatever) and PRs to enrol and collect this data? It seems to cut down on the admin effort at SusHack (http://sushack.co.uk/ and https://github.com/sushack/sushack.github.io/tree/master/_data).

**Comment by martinheidegger** [comment] 2015-05-01 12:18
@spikeheap We now have a script that collects the data, which means we should have only little overhead from now on, but I agree: this can be handled better.

**Comment by spikeheap** [comment] 2015-05-01 12:20
@martinheidegger, that sounds cool, I'd love to see it/them. We use meetup.com at the moment, but I'd love to just organise all our events through GH.

**Comment by martinheidegger** [comment] 2015-05-01 12:21
@spikeheap https://github.com/afronski/playground-nodejs/blob/master/tools/comments-gh-scraper

**Comment by afronski** [comment] 2015-05-01 12:31
Katowice (Silesia): http://www.meetup.com/NodeSchool-Silesia/events/222231203/

**Comment by grabbou** [comment] 2015-05-01 13:56
Wrocław: http://www.meetup.com/NodeSchool-Wroclaw/events/222231656/

**Comment by jeffjewiss** [comment] 2015-05-01 15:30
Toronto: https://ti.to/nodeschool-toronto/international-nodeschool-day-2015

**Comment by blakmatrix** [comment] 2015-05-01 16:59
@blakmatrix http://www.meetup.com/Seattle-NodeSchool/events/221984469/

On Friday, May 1, 2015, Jeff Jewiss notifications@github.com wrote:

> Toronto:
> https://ti.to/nodeschool-toronto/international-nodeschool-day-2015
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/international-day/issues/22#issuecomment-98157231
> .

## 

Farrin A. Reid
http://www.linkedin.com/in/farrinreid

**Comment by martinheidegger** [comment] 2015-05-01 17:34
Seattle (WA): http://www.meetup.com/Seattle-NodeSchool/events/221984469/

**Comment by martinheidegger** [comment] 2015-05-01 17:34
(@blakmatrix copied just for the script)

**Comment by a0viedo** [comment] 2015-05-01 17:55
@martinheidegger we just confirmed the venue, the event registration link will be up within the next few days.

**Comment by beltran-rubo** [comment] 2015-05-01 18:29
Seville: http://www.meetup.com/Bitnami-Sevilla/events/222186033/

**Comment by paulohp** [comment] 2015-05-05 13:50
Belo Horizonte: http://even.tc/nodeschool-bh

**Comment by martinheidegger** [comment] 2015-05-06 05:12
FYI: I have sent out a emails (using my freshly published [emailjs-cli](https://www.npmjs.com/package/emailjs-cli)), about.com messages, skype requests and a twitter message to start gathering all the links to the events.

**Comment by awaterma** [comment] 2015-05-06 05:25
Bainbridge Island (WA): http://www.meetup.com/IslandJS-Nodeschool/events/222090027/

**Comment by martinheidegger** [comment] 2015-05-06 05:26
@awaterma Thanks: I edited your text to fit our scraping script :stuck_out_tongue: moved link to enrollment. Cheers!

**Comment by ghost** [comment] 2015-05-06 05:38
Provo (Utah): http://www.meetup.com/Utah-Node-Ninjas/events/222202621/

**Comment by afronski** [comment] 2015-05-06 06:05
@bajtos I've removed notes after your enrollment entry (because of scraping script :wink:) - there is no problem with other services.

**Comment by mcollina** [comment] 2015-05-06 07:05
Milan: https://www.eventbrite.it/e/biglietti-nodeschool-italy-milano-16784771704

**Comment by afronski** [comment] 2015-05-06 07:06
@mcollina Thanks: I edited your text to fit our scraping script. :stuck_out_tongue: Cheers!

**Comment by mcollina** [comment] 2015-05-06 07:07
Ouch! :D

**Comment by grabbou** [comment] 2015-05-06 07:41
@martinheidegger side note - the repo link is dead... Any updates on that? Was going to add a terminal gui for this module using `yeoman-like` questions to make the process slightly more readable :)

**Comment by martinheidegger** [comment] 2015-05-06 07:44
@grabbou I am trying to figure out what you mean with "repo link"...

**Comment by grabbou** [comment] 2015-05-06 08:10
![screen shot 2015-05-06 at 10 10 08](https://cloud.githubusercontent.com/assets/2464966/7489532/1c0d9eb2-f3d8-11e4-9ad9-55b9862e4e1d.png)
Sometimes picture is worth more than a thousand of words

**Comment by martinheidegger** [comment] 2015-05-06 08:12
@grabbou sorry: fixed.

**Comment by finnp** [comment] 2015-05-06 10:36
Berlin: https://ti.to/nodeschool-berlin/8

**Comment by cronopio** [comment] 2015-05-06 16:40
We don't need any advance manage of information so we (Pereira Chapter) are going to use our website, nodeschool.io/pereira (under construction, hope push something tonight) and google forms and spreadsheets to manage the reservations.

**Comment by martinheidegger** [comment] 2015-05-06 16:46
Pereira: http://nodeschool.io/pereira

**Comment by a0viedo** [comment] 2015-05-06 18:55
Buenos Aires: https://ti.to/nodeschool/international-day-ba

**Comment by gmauricio** [comment] 2015-05-06 20:05
Manizales: http://www.meetup.com/ManizalesJS/events/222353574/

**Comment by martinheidegger** [comment] 2015-05-06 23:33
San Jose: http://www.meetup.com/costaricajs/events/222357068/

**Comment by az7arul** [comment] 2015-05-07 04:19
Dhaka: http://www.meetup.com/Dhaka-JS/events/222354776/

**Comment by max-mapper** [comment] 2015-05-07 17:12
OK only events with signup pages show up on the new globe site: http://nodeschool.io/globe/

so make sure and post your signup page here so it will show up on the globe!

the globe will get updated whenever the [enrollment scraper](https://github.com/nodeschool/international-day/tree/2015/enrollment-scraper) gets run and then the CSV from that gets checked into [gh-pages of this repo](https://github.com/nodeschool/globe)

**Comment by pricco** [comment] 2015-05-07 18:19
Montevideo: https://ti.to/sophilabs/nodeschool-23th-may-2015

**Comment by kwakayama** [comment] 2015-05-07 20:57
Stuttgart: https://ti.to/nodeschool-stuttgart/1

**Comment by ryanramage** [comment] 2015-05-07 22:43
Edmonton: https://ti.to/nodeschool-edmonton/nodeschool-edmonton-international-day

**Comment by martinheidegger** [comment] 2015-05-08 00:25
Melbourne: http://campjs.com/

**Comment by martinheidegger** [comment] 2015-05-08 00:25
@timoxley Didn't realise that Campjs is a signup site.

**Comment by martinheidegger** [comment] 2015-05-08 00:28
Medellín: http://www.meetup.com/MedellinJS/events/222031784

**Comment by martinheidegger** [comment] 2015-05-08 00:28
@julianduque Found your site!

**Comment by martinheidegger** [comment] 2015-05-08 00:37
Lisbon: http://www.meetup.com/require-lx/events/221544407/

**Comment by martinheidegger** [comment] 2015-05-08 00:39
@sericaia Found Lisbon too...

**Comment by martinheidegger** [comment] 2015-05-08 00:42
Dublin: http://www.meetup.com/Nodeschool-Dublin-Meetup/events/221183159/

**Comment by martinheidegger** [comment] 2015-05-08 00:43
@no9 Found Dublin.

**Comment by martinheidegger** [comment] 2015-05-08 01:02
Western Massachusetts (MA): https://ti.to/nodeschool-western-massachusetts/nodeschool-international-day-2015/

**Comment by martinheidegger** [comment] 2015-05-08 01:02
@Sequoia found Western Mass

**Comment by Sequoia** [comment] 2015-05-08 01:23
the google calendar _should_ have all of this info.

**Comment by martinheidegger** [comment] 2015-05-08 02:43
Which Google calendar are you talking about?

**Comment by keokilee** [comment] 2015-05-08 05:01
Honolulu (Hawaii): https://www.facebook.com/events/387996224729628/

Sorry for the delay!

**Comment by llkats** [comment] 2015-05-08 06:13
San Francisco (California): https://ti.to/nodeschoolsf/international-day-may-23rd

Many apologies as well for the delay!

**Comment by diegowifi** [comment] 2015-05-08 16:19
Monterrey: https://ti.to/nodeschoolmty/international-day

**Comment by martinheidegger** [comment] 2015-05-10 11:40
@iamchathu ping

**Comment by a0viedo** [comment] 2015-05-10 22:31
many confirmations are still missing:
@ralucas
@davyengone
@hrayatnia
@jonotron
@usmantahirr
@makenai
@carlodicelico
@colinloretz
@marinintim
@forres
@asbjornenge
@chitopolo

**Comment by martinheidegger** [comment] 2015-05-10 23:09
@iamchathu as well

**Comment by martinheidegger** [comment] 2015-05-11 03:03
@ralucas : https://github.com/nodeschool/denver-boulder/issues/15
@davyengone  (Sent mail)
@hrayatnia (Sent mail)
~~@jonotron : https://github.com/nodeschool/kamloops/issues/2~~
@usmantahirr : https://github.com/nodeschool/Lahore/issues/3
~~@makenai : https://github.com/nodeschool/vegas/issues/2~~
@carlodicelico : https://github.com/nodeschool/portland-me/issues/13
@colinloretz : https://github.com/nodeschool/reno/issues/1
@marinintim : https://github.com/nodeschool/spb/issues/1
@forres : https://github.com/nodeschool/Santiago/issues/2
~~@asbjornenge : https://github.com/nodeschool/stavanger/issues/6~~
~~@diegowifi : https://github.com/nodeschool/mty/issues/3~~
@chitopolo : https://github.com/nodeschool/Cochabamba/issues/1
@iamchathu (Sent mail)

**Comment by martinheidegger** [comment] 2015-05-11 03:06
Monterrey: https://ti.to/nodeschoolmty/international-day

**Comment by iancrowther** [comment] 2015-05-11 16:32
Enrollment has now closed.

Chapters who have not setup up a registration page inc start/finish times will not be included in the minifilm, day stats and rollcall.

We have a LOT to manage now and cant chase everyone for details as we need to prepare the day.

Many thanks to everyone so far for their contributions, please take a look at the issues and chip in.  We really need your help in the run up to the event.

**Comment by jonotron** [comment] 2015-05-11 20:51
Kamloops: https://www.picatic.com/nodeschoolintlkamloops

I realize this is late, but here for posterity anyways.

**Comment by ghost** [comment] 2015-05-12 05:20
Chiang Mai: https://www.facebook.com/events/493163420832014/

**Comment by iancrowther** [comment] 2015-05-12 12:30
@jonotron @kytwb your all good..

**Comment by colinloretz** [comment] 2015-05-12 18:14
Reno: https://www.eventbrite.com/e/nodeschool-reno-may-2015-tickets-16932123437

**Comment by Sequoia** [comment] 2015-05-13 13:44
@martinheidegger the secret one found here: :smile_cat: https://github.com/nodeschool/nodeschool.github.io/blob/master/js/events.js#L9

**Comment by iancrowther** [comment] 2015-05-14 11:17
@Sequoia blimey.. is the form still alive?

**Comment by Sequoia** [comment] 2015-05-14 11:52
@iancrowther
Yeah, and it's driving the event map :)

> If you're organizing a NodeSchool event, add it to this site by filling out this form.

http://nodeschool.io/events

**Comment by martinheidegger** [comment] 2015-05-14 12:43
The google spreadsheet (not calendar!) is still intact, but since there is no direct relationship between event entry and chapter I didn't ask to put the sign up page there. In fact I think i will send a short PR there :)

**Comment by iancrowther** [comment] 2015-05-14 13:13
@Sequoia ah yes of course.. thanks for pointing that out :-)

**Comment by iancrowther** [comment] 2015-05-22 18:24
Many thanks to everyone who collaborated here

**Closed as completed** 2015-05-23 03:21 UTC
